# Write traced art (and regions, if any) as an ES module next to the page.
# See ../SKILL.md for what each export is and how the page draws it.
import json


def module(page, trace, regions=None):
    q = lambda s: "'" + s + "'"
    lines = [
        '// %s · traced art for %s.js' % (page['title'], page['page']),
        '// Traced from the reference screenshot (%d x %d px): flat colour layers' % tuple(page['reference']['size']),
        "// back to front, then the grey brush and the black pen as filled shapes so the",
        "// line weight is the pen's.",
        '// Art coordinates are half reference pixels, traced at 2x so edges fall between',
        '// pixels; region coordinates are whole reference pixels. Generated by the',
        '// trace-reference-art skill from its pages/%s.json: regenerate, don\'t hand-edit.' % page['page'],
        '',
        'export const LAYERS = [',
    ]
    lines += ['  [%s, %s],' % (q(c), q(d)) for c, d in trace['layers']]
    lines += [']', '',
              '// the grey brush the hatching is done in, under the pen',
              'export const BRUSH = [%s, %s]' % (q(trace['brush'][0]), q(trace['brush'][1])), '',
              'export const INK = %s' % q(trace['ink']), '',
              '// the pen is blacker than the rest of the book',
              'export const INK_COLOR = %s' % q(trace['inkColor']), '']
    if regions:
        lines += ['// what shows where an item has been taken away',
                  'export const FLOOR = %s' % q(regions['floor']), '',
                  'export const PIECES = [']
        lines += ['  { kind: %s, x: %d, y: %d, region: %s },' % (q(k), x, y, q(r)) for k, x, y, r in regions['pieces']]
        lines += [']']
    lines += ['']
    return '\n'.join(lines)
