# Write the traced data as an ES module next to the page.
import json, sys
t = json.load(open(sys.argv[1])); pc = json.load(open(sys.argv[2]))
q = lambda s: "'" + s + "'"
lines = [
    '// Chapter 1, page 7 · traced art for ch01-couch.js',
    '// Traced from the reference screenshot (1200 x 2670 px): flat colour layers',
    "// back to front, then the grey brush and the black pen as filled shapes so the",
    "// line weight is the pen's.",
    '// Art coordinates are half reference pixels, traced at 2x so edges fall between',
    '// pixels; piece regions are whole reference pixels. Generated by',
    '// scripts/trace-couch — regenerate rather than hand-edit.',
    '',
    'export const LAYERS = [',
]
lines += ['  [%s, %s],' % (q(c), q(d)) for c, d in t['layers']]
lines += [']', '',
          '// the grey brush the hatching is done in, under the pen',
          'export const BRUSH = [%s, %s]' % (q(t['brush'][0]), q(t['brush'][1])), '',
          'export const INK = %s' % q(t['ink']), '',
          '// the pen is blacker than the rest of the book',
          'export const INK_COLOR = %s' % q(t['inkColor']), '',
          '// what shows once a piece is eaten: its region, filled with the tray floor',
          'export const FLOOR = %s' % q(pc['floor']), '',
          'export const PIECES = [']
lines += ['  { kind: %s, x: %d, y: %d, region: %s },' % (q(k), x, y, q(r)) for k, x, y, r in pc['pieces']]
lines += [']', '']
open(sys.argv[3], 'w').write('\n'.join(lines))
